import type { FlavorName } from "./palettes";
import { palettes, defaultFlavor } from "./palettes";
import type { ColorSchemeColors } from "./color-scheme";
import { ColorScheme } from "./color-scheme";
import { typography } from "./typography";
import { spacing } from "./spacing";
import { geometry } from "./geometry";

export interface TypographyOverrides {
  family?: string;
  familyDisplay?: string;
  familyMono?: string;
}

export interface ThemeOverrides {
  colorScheme?: Partial<ColorSchemeColors>;
  typography?: TypographyOverrides;
}

export class ThemeData {
  readonly name: string;
  readonly colorScheme: ColorScheme;
  readonly typography: {
    readonly family: string;
    readonly familyDisplay: string;
    readonly familyMono: string;
  };
  readonly spacing = spacing;
  readonly geometry = geometry;
  readonly isDark: boolean;

  private constructor(
    name: string,
    colorScheme: ColorScheme,
    isDark: boolean,
    typographyOverrides?: TypographyOverrides,
  ) {
    this.name = name;
    this.colorScheme = colorScheme;
    this.isDark = isDark;
    this.typography = {
      family: typographyOverrides?.family ?? typography.family,
      familyDisplay: typographyOverrides?.familyDisplay ?? typography.familyDisplay,
      familyMono: typographyOverrides?.familyMono ?? typography.familyMono,
    };
  }

  // ── Fábricas ──

  static dark(overrides?: ThemeOverrides): ThemeData {
    const scheme = overrides?.colorScheme
      ? ColorScheme.fromFlavor(defaultFlavor).copyWith(overrides.colorScheme)
      : ColorScheme.fromFlavor(defaultFlavor);
    return new ThemeData("dark-custom", scheme, true, overrides?.typography);
  }

  static light(overrides?: ThemeOverrides): ThemeData {
    const scheme = overrides?.colorScheme
      ? ColorScheme.fromFlavor("latte").copyWith(overrides.colorScheme)
      : ColorScheme.fromFlavor("latte");
    return new ThemeData("light-custom", scheme, false, overrides?.typography);
  }

  static fromFlavor(flavor: FlavorName, overrides?: ThemeOverrides): ThemeData {
    const isDark = flavor !== "latte" && flavor !== "vercel-light";
    const scheme = overrides?.colorScheme
      ? ColorScheme.fromFlavor(flavor).copyWith(overrides.colorScheme)
      : ColorScheme.fromFlavor(flavor);
    return new ThemeData(flavor, scheme, isDark, overrides?.typography);
  }

  static brand(seed: string, isDark: boolean = true, overrides?: ThemeOverrides): ThemeData {
    const scheme = overrides?.colorScheme
      ? ColorScheme.brand(seed).copyWith(overrides.colorScheme)
      : ColorScheme.brand(seed);
    return new ThemeData("brand", scheme, isDark, overrides?.typography);
  }

  // ── Derivação ──

  copyWith(overrides: ThemeOverrides): ThemeData {
    return new ThemeData(
      this.name,
      overrides.colorScheme ? this.colorScheme.copyWith(overrides.colorScheme) : this.colorScheme,
      this.isDark,
      overrides.typography ? { ...this.typography, ...overrides.typography } : this.typography,
    );
  }

  // ── Output: QML overrides (injetado como _brandTheme context property) ──

  toQMLOverrides(): Record<string, string> {
    const cs = this.colorScheme.toRecord();
    const result: Record<string, string> = {};
    for (const [key, value] of Object.entries(cs)) {
      result[`scheme${key.charAt(0).toUpperCase() + key.slice(1)}`] = value;
    }
    result["isDark"] = this.isDark ? "true" : "false";
    if (this.typography.family !== typography.family) {
      result["typeFamily"] = this.typography.family;
    }
    if (this.typography.familyDisplay !== typography.familyDisplay) {
      result["typeFamilyDisplay"] = this.typography.familyDisplay;
    }
    if (this.typography.familyMono !== typography.familyMono) {
      result["typeFamilyMono"] = this.typography.familyMono;
    }
    return result;
  }

  // ── Output: CSS custom properties ──

  toCSS(): string {
    const lines: string[] = [];
    lines.push("/* Generated by @mocha/tokens ThemeData.toCSS() */");
    if (this.isDark) {
      lines.push(':root[data-theme="custom-dark"], :root {');
    } else {
      lines.push(':root[data-theme="custom-light"] {');
    }
    lines.push(this.colorScheme.toCSSVariables());
    if (this.typography.family !== typography.family) {
      lines.push(`  --ctp-font-family: '${this.typography.family}', -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;`);
    }
    if (this.typography.familyDisplay !== typography.familyDisplay) {
      lines.push(`  --ctp-font-family-display: '${this.typography.familyDisplay}', var(--ctp-font-family);`);
    }
    if (this.typography.familyMono !== typography.familyMono) {
      lines.push(`  --ctp-font-family-mono: '${this.typography.familyMono}', monospace;`);
    }
    lines.push("}");
    return lines.join("\n");
  }
}
