import { existsSync, readFileSync } from "node:fs";
import { join, resolve } from "node:path";

// Dynamic import — will be generated by napi build
let native: any;
let nativeLoaded = false;

async function loadNative(): Promise<any> {
  if (nativeLoaded) return native;
  try {
    native = await import("./index.js");
    nativeLoaded = true;
    return native;
  } catch {
    throw new Error(
      "@mocha/native not built. Run: cd packages/native && npx napi build --platform --release"
    );
  }
}

export interface NativeApp {
  loadQML(qml: string, basePath?: string): void;
  setProperty(obj: string, property: string, value: string | number | boolean): void;
  getProperty(obj: string, property: string): string;
  exec(): number;
  quit(): void;
  poll(): boolean;
  processEvents(): void;
}

class NativeAppImpl implements NativeApp {
  private _engine: number = 0;
  private _rootObject: number = 0;
  private _initialized = false;

  async init(): Promise<void> {
    if (this._initialized) return;
    const n = await loadNative();

    n.nativeAppCreate();
    this._engine = n.nativeEngineCreate();
    this._initialized = true;
  }

  loadQML(qml: string, basePath?: string): void {
    if (!this._initialized) throw new Error("Native app not initialized. Call init() first.");
    const n = native;
    const bp = basePath ?? process.cwd();
    n.nativeEngineLoad(this._engine, qml, bp);

    try {
      this._rootObject = n.nativeEngineRootObject(this._engine);
    } catch {
      console.warn("QML loaded but no root object found (window may not be visible yet)");
    }
  }

  setProperty(obj: string, property: string, value: string | number | boolean): void {
    if (!this._rootObject) throw new Error("No root object. Call loadQML first.");
    const n = native;
    if (typeof value === "number") {
      if (Number.isInteger(value)) {
        n.nativeObjectSetInt(this._rootObject, property, value);
      } else {
        throw new Error("Float properties not yet supported");
      }
    } else if (typeof value === "boolean") {
      n.nativeObjectSetBool(this._rootObject, property, value);
    } else {
      n.nativeObjectSetProperty(this._rootObject, property, String(value));
    }
  }

  getProperty(obj: string, property: string): string {
    if (!this._rootObject) throw new Error("No root object. Call loadQML first.");
    return native.nativeObjectGetProperty(this._rootObject, property);
  }

  exec(): number {
    return native.nativeAppExec();
  }

  quit(): void {
    native.nativeAppQuit();
  }

  poll(): boolean {
    // poll via processEvents + always return true until quit
    try {
      native.nativeProcessEvents();
      return true;
    } catch {
      return false;
    }
  }

  processEvents(): void {
    native.nativeProcessEvents();
  }
}

let _app: NativeAppImpl | null = null;

export async function createNativeApp(): Promise<NativeApp> {
  if (_app) return _app;
  _app = new NativeAppImpl();
  await _app.init();
  return _app;
}

export function getNativeApp(): NativeApp | null {
  return _app;
}
