import { existsSync, readFileSync } from "node:fs";
import { join, resolve } from "node:path";

// Dynamic import — will be generated by napi build
let native: any;
let nativeLoaded = false;

async function loadNative(): Promise<any> {
  if (nativeLoaded) return native;
  try {
    native = await import("./index.js");
    nativeLoaded = true;
    return native;
  } catch {
    throw new Error(
      "@mocha/native not built. Run: cd packages/native && npx napi build --platform --release"
    );
  }
}

export interface QmlNode {
  id: number;
  className: string;
  objectName: string;
  children: QmlNode[];
}

export interface QmlProperty {
  name: string;
  type: string;
  value: string;
  readable: boolean;
  writable: boolean;
}

export interface NativeApp {
  loadQML(qml: string, basePath?: string): void;
  setProperty(obj: string, property: string, value: string | number | boolean): void;
  getProperty(obj: string, property: string): string;
  exec(): number;
  quit(): void;
  poll(): boolean;
  processEvents(): void;

  // QML Native Tree Inspector
  registerAppObjects(): void;
  listRootObjects(): QmlNode[];
  listChildren(objId: number): QmlNode[];
  getQmlProperty(objId: number, name: string): string;
  getQmlProperties(objId: number): QmlProperty[];
  setQmlProperty(objId: number, name: string, value: string): void;
  get typeName(): string;
}

class NativeAppImpl implements NativeApp {
  private _engine: number = 0;
  private _rootObject: number = 0;
  private _initialized = false;

  async init(): Promise<void> {
    if (this._initialized) return;
    const n = await loadNative();

    n.nativeAppCreate();
    this._engine = n.nativeEngineCreate();
    this._initialized = true;
  }

  loadQML(qml: string, basePath?: string): void {
    if (!this._initialized) throw new Error("Native app not initialized. Call init() first.");
    const n = native;
    const bp = basePath ?? process.cwd();
    n.nativeEngineLoad(this._engine, qml, bp);

    try {
      this._rootObject = n.nativeEngineRootObject(this._engine);
    } catch {
      console.warn("QML loaded but no root object found (window may not be visible yet)");
    }
  }

  setProperty(obj: string, property: string, value: string | number | boolean): void {
    if (!this._rootObject) throw new Error("No root object. Call loadQML first.");
    const n = native;
    if (typeof value === "number") {
      if (Number.isInteger(value)) {
        n.nativeObjectSetInt(this._rootObject, property, value);
      } else {
        throw new Error("Float properties not yet supported");
      }
    } else if (typeof value === "boolean") {
      n.nativeObjectSetBool(this._rootObject, property, value);
    } else {
      n.nativeObjectSetProperty(this._rootObject, property, String(value));
    }
  }

  getProperty(obj: string, property: string): string {
    if (!this._rootObject) throw new Error("No root object. Call loadQML first.");
    return native.nativeObjectGetProperty(this._rootObject, property);
  }

  exec(): number {
    return native.nativeAppExec();
  }

  quit(): void {
    native.nativeAppQuit();
  }

  poll(): boolean {
    // poll via processEvents + always return true until quit
    try {
      native.nativeProcessEvents();
      return true;
    } catch {
      return false;
    }
  }

  processEvents(): void {
    native.nativeProcessEvents();
  }

  // ── QML Native Tree Inspector ──

  registerAppObjects(): void {
    if (!this._initialized) return;
    native.qmlRegisterAppObjects(this._engine);
  }

  listRootObjects(): QmlNode[] {
    if (!this._initialized) return [];
    const ids: number[] = native.qmlListRootObjects();
    return ids.map((id) => this._buildQmlNode(id));
  }

  listChildren(objId: number): QmlNode[] {
    if (!this._initialized) return [];
    const ids: number[] = native.qmlListChildren(objId);
    return ids.map((id) => this._buildQmlNode(id));
  }

  getQmlProperty(objId: number, name: string): string {
    return native.qmlGetProperty(objId, name) ?? "";
  }

  getQmlProperties(objId: number): QmlProperty[] {
    const json = native.qmlGetAllProperties(objId);
    try { return JSON.parse(json); } catch { return []; }
  }

  setQmlProperty(objId: number, name: string, value: string): void {
    native.qmlSetProperty(objId, name, value);
  }

  get typeName(): string {
    return "";
  }

  private _buildQmlNode(id: number): QmlNode {
    const className = native.qmlGetTypeName(id) ?? "Unknown";
    const objectName = native.qmlGetObjectName(id) ?? "";
    const childIds: number[] = native.qmlListChildren(id) ?? [];
    return {
      id,
      className,
      objectName,
      children: childIds.map((cid) => this._buildQmlNode(cid)),
    };
  }
}

let _app: NativeAppImpl | null = null;

export async function createNativeApp(): Promise<NativeApp> {
  if (_app) return _app;
  _app = new NativeAppImpl();
  await _app.init();
  return _app;
}

export function getNativeApp(): NativeApp | null {
  return _app;
}
